version: '3.8'

services:
  postgresql:
    container_name: postgresql
    build:
      context: ./src/postgreSQL
    restart: always
    #environment:
    #  POSTGRES_DB: ${POSTGRES_DB}
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    build:
      context: ./src/pgadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgresql
    env_file: .env

  nestjs-app:
    container_name: nestjs-app
    build:
      context: ./src/nestjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user42/Bureau/VolumeTranscendance
