version: '3.8'

services:
  postgresql:
    container_name: postgresql
    build:
      context: ./src/postgreSQL
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    build:
      context: ./src/pgAdmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgresql
    env_file: .env

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user42/Bureau/VolumeTranscendance
