FROM dpage/pgadmin4
RUN echo "\033[1;33m============================================\033[0m"
RUN echo "\033[1;35m----------Installation de pgAdmin-----------\033[0m"
RUN echo "\033[1;33m============================================\033[0m"
RUN echo "\033[1;33m============================================\033[0m"
RUN echo "\033[1;35m------------Gestion des var d'env-----------\033[0m"
RUN echo "\033[1;33m============================================\033[0m"
ENV PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
ENV PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
RUN echo "\033[1;33m============================================\033[0m"
RUN echo "\033[1;35m-------------Expose du port 8080------------\033[0m"
RUN echo "\033[1;33m============================================\033[0m"
EXPOSE 8080
RUN echo "\033[1;33m============================================\033[0m"
RUN echo "\033[1;35m----------Fin du Dockerfile pgAdmin---------\033[0m"
RUN echo "\033[1;33m============================================\033[0m"